# Generated by Django 2.1.1 on 2018-11-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20181014_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('SK', 'Skeleton'), ('UN', 'Unlimited'), ('MA', 'Master')], default='SK', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
    ]
